# Generated by Django 4.2.6 on 2023-10-30 04:03

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_subject', models.CharField(max_length=50, null=True)),
                ('p_slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('p_body', ckeditor.fields.RichTextField()),
                ('p_status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='p', max_length=10)),
                ('p_created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('p_published_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('p_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('p_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autherposts', to=settings.AUTH_USER_MODEL)),
                ('p_tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('-p_published_at',),
                'unique_together': {('p_subject', 'p_published_at')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_body', ckeditor.fields.RichTextField()),
                ('c_owner_name', models.CharField(max_length=50, null=True)),
                ('c_owner_email', models.EmailField(max_length=254, null=True)),
                ('c_status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='p', max_length=10)),
                ('c_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('p_published_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('c_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('c_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcomments', to='blog.post')),
            ],
            options={
                'ordering': ('-p_published_at',),
            },
        ),
    ]
